;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname HW0) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(require 2htdp/image)

#|
  Ctrl+F
  Type '||' find whole solution for question
  Type '|=' to find function
  Type ';;-' to find test
|#

#||-------------------
---------(a)----------
--------------------|#

(* (- (* 5 3)
      (- 8 (string-length (string-append "CS" "1101"))))
   (/ 48 16))

;(* (- 15
;      (- 8 (string-length (string-append "CS" "1101"))))
;   (/ 48 16))

;(* (- 15
;      (- 8 (string-length "CS1101")))
;   (/ 48 16))

;(* (- 15 (- 8 6)) (/ 48 16))

;(* (- 15 2) (/ 48 16))

;(* 13 (/ 48 16))

;(* 13 3)

;39

#||-------------------
---------(b)----------
--------------------|#

(define (cube n)
  (* n n n))

(if (> (cube 2) (cube (/ 12 4)))
    (- 105 107)
    (sqrt (+ 1 (* 5 3))))

;(if (> 8 (cube (/ 12 4)))
;    (- 105 107)
;    (sqrt (+ 1 (* 5 3))))

;(if (> 8 (cube 3))
;    (- 105 107)
;    (sqrt (+ 1 (* 5 3))))

;(if (> 8 27)
;    (- 105 107)
;    (sqrt (+ 1 (* 5 3))))

;(if #false
;    (- 105 107)
;    (sqrt (+ 1 (* 5 3))))

;(sqrt (+ 1 15))

;(sqrt 16)

;4


#||-------------------
-----kaleidoscope-----
--------------------|#

#|=--kaleidoscope---|#
;; kaleidoscope: Image --> Image

;; consumes an image and produces an centrosymmetric image that consists of 4 copies of the original image

(define (kaleidoscope hwImg)
        (above (beside (flip-horizontal hwImg) hwImg) (rotate 180 (beside (flip-horizontal hwImg) hwImg))))

;;-------TEST-------;;
; None

#||-------------------
-------Zoo Tour-------
--------------------|#

#|=----expenses-----|#
;; expenses: Number --> Number

;; consumes the number of chaperones and the number of students at an event
;; and produces the cost to the zoo to conduct the tour

(define (expenses chaperon student)
        (* (+ chaperon student) 102))

;;-------TEST-------;;
(check-expect (expenses 10 10) 2040)
(check-expect (expenses 1 1) 204)

#|=-----income------|#
;; income: Number --> Number

;; consumes the number of chaperones and the number of students
;; and the price per ticket and produces the monies generated by ticket sales

(define (income chaperon student ticketPrice)
        (* (+ chaperon student) ticketPrice))

;;-------TEST-------;;
(check-expect (income 10 10 200) 4000)
(check-expect (income 1 1 200) 400)

#|=----proceeds-----|#
;; proceeds: Number --> Number

;; consumes the number of attendees and the price per ticket
;; and produces the profit for the event

(define (proceeds attendees ticketPrice)
        (- (* attendees ticketPrice) (* attendees 102)))

;;-------TEST-------;;
(define (proceedsTest attendees ticketPrice)
        (- (income (/ attendees 2) (/ attendees 2) ticketPrice) (expenses (/ attendees 2) (/ attendees 2))))

(check-expect (proceeds 20 200) 1960)
(check-expect (proceeds 2 200) 196)
(check-expect (proceeds 20 200) (proceedsTest 20 200))
(check-expect (proceeds 2 200) (proceedsTest 2 200))

#||-------------------
--total-cost-of-house-
--------------------|#

; Constants
(define rate 0.04)
(define time 15)
(define fees 3000)

#|=-----amount------|#
;; amount: Number --> Number

;; consumes the purchase price of a house and the amount of the down-payment
;; and produces the principal(Helper Func)

(define (amount housePrice downPayment) (- housePrice downPayment))

;;-------TEST-------;;
(check-expect (amount 2000 1000) 1000)
(check-expect (amount 20 10) 10)

#|=----interest-----|#
;; interest: Number --> Number

;; consumes the purchase price of a house and the amount of the down-payment
;; and produce the interest(Helper Func)

(define (interest housePrice downPayment)
        (* rate (- housePrice downPayment) time))

;;-------TEST-------;;
(check-expect (interest 2000 1000) 600)
(check-expect (interest 20 10) 6)

#|=total-cost-of-house|#
;; total-cost-of-house: Number --> Number

;; consumes the purchase price of a house and the amount of the down-payment
;; and produces the grand total paid by the buyer for the house

(define (total-cost-of-house housePrice downPayment)
        (+ (interest housePrice downPayment) fees housePrice))

;;-------TEST-------;;
(check-expect (total-cost-of-house 2000 1000) 5600)
(check-expect (total-cost-of-house 20 10) 3026)